{% set name = "leocad" %}
{% set version = "21.06" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/leozide/leocad/archive/v{{ version }}.tar.gz
  sha256: bd28c47f920fa1bc458b6e5f476b93ccc1aa40e30158a3dd2397368cc3d79099
  patches:
    - ldraw-library-path.patch
    - patch-project-osx.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    # Required to link with libGL
    - libglu                         # [linux]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}        # [linux]
    - {{ cdt('libxdamage') }}        # [linux]
    - {{ cdt('libxxf86vm') }}        # [linux]
    - {{ cdt('libxext') }}           # [linux]
  host:
    - qt-main
    - ldraw-parts
    - xorg-libxfixes                 # [linux]
    - zlib
  run:
    - ldraw-parts

test:
  commands:
    - test -f ${PREFIX}/bin/leocad

about:
  home: https://github.com/leozide/leocad
  license: GPL-2.0-only
  license_family: GPL
  license_file: docs/COPYING.txt
  summary: 'A CAD program for creating virtual LEGO models'
  description: |
    LeoCAD has an intuitive interface that is designed to allow
    new users to start creating new models without having to spend
    too much time learning the application.
    At the same time, it has a rich feature set that
    enables experienced users to build models by using
    techniques that are more advanced.
  doc_url: https://www.leocad.org/
  dev_url: https://www.leocad.org/

extra:
  recipe-maintainers:
    - SylvainCorlay
    - derthorsten
